### ISSUE TITLE
Replace a dead link.

### ISSUE THREAD

**Issue by ghost** [dmbaturin/baturin.org#1]
The dead link to https://www.astro.umd.edu/~avondale/extra/Humor/ComputerHumor/PeaSea.html
could be replaced with
http://web.archive.org/web/20170130041620/https://www.astro.umd.edu/~avondale/extra/Humor/ComputerHumor/PeaSea.html

**Comment by dmbaturin** [comment]
Fixed, thanks!

I wonder why she removed those pages. Her site is still online and was updated no earlier than 2019.

**Comment by ghost** [comment]
I emailed her with a question. Not sure if she's going to respond.
